spring:
  profiles:
    active: qa

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-stacktrace: always
    tomcat:
      max-threads: 250
      max-connections: 10000
      min-spare-threads: 20
  servlet:
    context-path: /kmdk

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: false
    prometheus:
      enabled: true
      cache:
        time-to-live: 0ms
  info:
    defaults:
      enabled: true
    git:
      mode: full
  metrics:
    export:
      prometheus:
        descriptions: true
        step: 1m

mybatis-plus:
  global-config:
    db-config:
      db-type: mysql
  type-aliases-package: 'com.mq.kafka.demo.entity'
  type-handlers-package: 'com.mq.kafka.demo.listener'
  #  type-enums-package: 'com.mq.kafka.demo.enum'
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    aggressive-lazy-loading: true
    cache-enabled: true
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
#    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
#    default-fetch-size: 100
#    default-statement-timeout: 30