info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

server:
    port: 80

management:
  server:
    port: 80
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: false
  info:
    defaults:
      enabled: true
    git:
      mode: full

spring:
  main:
    web-application-type: reactive
  application:
    name: '${rootArtifactId} (qa)'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cnedtechpdpgsdb01qa.c4qxob5ca5uq.rds.cn-north-1.amazonaws.com.cn:5432/mt_content_dev
    username: mocktestqa
    password: 'efef@123'
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
  redis:
    master: cne1qapdredis1-001.nsmena.0001.cnn1.cache.amazonaws.com.cn:6379
    slaves:
      - cne1qapdredis1-002.nsmena.0001.cnn1.cache.amazonaws.com.cn:6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 10000
        max-wait: 5000
        max-idle: 30
        min-idle: 5
    timeout: 5000
    app-ttl: 43200
    app-enabled: true

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36}.%M() @%L - %msg%n'
    level: DEBUG
  level:
    root: DEBUG
    org:
      springframework:
        web: DEBUG
      mybatis: DEBUG

mybatis:
  typeAliasesPackage: ${groupId}.repository.entity
  #mapperLocations: classpath:mapper/*.xml
  #type-handlers-package: com.eflabs.authsvc.app.
  configuration:
      cacheEnabled: true
      lazyLoadingEnabled: true
      aggressiveLazyLoading: true
#      map-underscore-to-camel-case: true
#      default-fetch-size: 100
#      default-statement-timeout: 30

jwt:
  private-key: 'keys/rsa/private_key.pem'
  public-key: 'keys/rsa/public_key.pem'





