info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

server:
    port: 80

management:
  server:
    port: 80
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: false
  info:
    defaults:
      enabled: true
    git:
      mode: full

spring:
  main:
    web-application-type: reactive
  application:
    name: '${rootArtifactId} (stgsg)'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/xxxx
    username: xxxx
    password: 'xxxx'
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
  redis:
    master: 127.0.0.1:6379
    slaves:
      - 127.0.0.1:63791
    database: 0
    password:
    lettuce:
      pool:
        max-active: 10000
        max-wait: 5000
        max-idle: 30
        min-idle: 5
    timeout: 5000
    app-ttl: 43200
    app-enabled: true

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36}.%M() @%L - %msg%n'
    level: DEBUG
  level:
    root: DEBUG
    org:
      springframework:
        web: DEBUG
      mybatis: DEBUG

mybatis:
  typeAliasesPackage: ${groupId}.repository.entity
  #mapperLocations: classpath:mapper/*.xml
  #type-handlers-package: ${groupId}.app.
  configuration:
      cacheEnabled: true
      lazyLoadingEnabled: true
      aggressiveLazyLoading: true
#      map-underscore-to-camel-case: true
#      default-fetch-size: 100
#      default-statement-timeout: 30

jwt:
  private-key: 'keys/rsa/private_key.pem'
  public-key: 'keys/rsa/public_key.pem'





