#!groovy
library identifier: 'jenkinssharedlib@tc/v2', retriever: modernSCM(
  [$class       : 'GitSCMSource',
   remote       : 'ssh://git@bitbucket.xxxx.cn:7999/elab/jenkinssharedlib.git',
   credentialsId: '6eb8497e-6687-41e7-8a3c-1856eb98116e'])

config = [
  service           : 'learning-plan',                   // docker-compose service for building image.
  imageRepo         : 'edtech-kt/learning-plan',
  teamsConnectorName: 'Platform Channel',
  teamsConnectorUrl:  'XXXX'
]

pipeline {
  options {
    disableConcurrentBuilds()
    timeout(time: 15, unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '20'))
    office365ConnectorWebhooks([[
                                  name: config.teamsConnectorName, url: config.teamsConnectorUrl,
                                  notifySuccess: true, notifyFailure: true, notifyRepeatedFailure: true, notifyUnstable: true, notifyBackToNormal: true
                                ]])
  }
  triggers {
    pollSCM('H/5 * * * *')
  }
  agent {
    kubernetes {
      label 'java11-slave'
      defaultContainer 'jnlp'
      yaml ktJava11PodTemplate()
    }
  }
  stages {
    stage('Prepare') {
      steps {
        container('maven') {
          script {
            def branch = ktGetTriggerBranch()
            def commitHash = ktGetCommitHash()
            IMAGE_TAG = ktGetBranchWithHashTag(branch, commitHash)
          }
        }
      }
    }
    stage('Build & Package') {
      steps {
        container('maven') {
          sh """
          mvn -B verify sonar:sonar
          """
        }
      }
    }
    stage('Build & Push Image') {
      steps {
        script {
          container('docker') {
            ktBuildAndPushImage(config.service, config.imageRepo, IMAGE_TAG)
          }
        }
      }
    }
  }
}
