#!groovy
library identifier: 'jenkinssharedlib@tc/v3', retriever: modernSCM(
  [$class       : 'GitSCMSource',
   remote       : 'ssh://git@bitbucket.xxxxxx.cn:7999/elab/jenkinssharedlib.git',
   credentialsId: '6f6f2853-94ac-4d4e-a714-fb0768580952'])

sharedCIPipelineJava {
  podTemplate = ktPodTemplate('java8': true)

  service = 'mq-spring-kafka-demo'
  imageRepo = 'pd/mq-spring-kafka-demo'
  registries = ['AWS_CN':true, 'AWS_SG':false, 'TC_CN':false]

  qaDeployJob  = "PD-CN-MQ-KAFKA-DEMO-QA-Deploy"
  stgDeployJob = "PD-CN-MQ-KAFKA-DEMO-STG-Deploy"

  teamsConnectorName = 'XXXX'
  teamsConnectorUrl = 'XXXX'
}